services:
  ollama:
    volumes:
      - ollama-local:/root/.ollama
    container_name: ollama
    environment:
      OLLAMA_NUM_PARALLEL: 1
    ports:
      - 11434:11434
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui
    container_name: open-webui
    volumes:
      - openwebui-local:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3000:8080
    environment:
      WEBUI_AUTH: 'false'
      WEBUI_SECRET_KEY: 'top-secret'
      OLLAMA_BASE_URL: 'http://ollama:11434'
#    extra_hosts:
#      - host.docker.internal:host-gateway
    restart: unless-stopped
volumes:
  ollama-local : {} 
  openwebui-local: {} 
